title: "Bruno Teixeira"
email: "brunoalexandre3@hotmail.com"
baseurl: ""
twitter_username: BTeixeira1996

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
highlighter: rouge

paginate: 8
paginate_path: "/projects/page:num/"
plugins: [jekyll-paginate]

plugins_dir:
  - jekyll-paginate
  - jekyll-compress-images
  - rouge
  - kramdown
  - jekyll-paginate

# Struct

footer: yes

nav:
 - name: "about"  
   link: "/"
 # - name: "projects"
 #   link: "/projects/"
 - name: "writeups"
   link: "/writeups"
 - name: "publications"
   link: "/publications"

collections:
  writeups:
    output: true
  publications:
    output: true
    
social:
  - name: twitter/BTeixeira1996
    icon: fab fa-twitter
    url: https://twitter.com/BTeixeira1996
  - name: linkedin/bruno-teixeira
    icon: fab fa-linkedin
    url: https://www.linkedin.com/in/bruno-teixeira-1553b4a1/
  - name: github/BrunoTeixeira1996
    icon: fab fa-github
    url: https://github.com/BrunoTeixeira1996
  - name: htb/zebisnaga
    icon: fa-solid fa-cube
    url: https://app.hackthebox.com/profile/59575
