baseURL: http://example.org/
languageCode: en-us
title: Bruno Blog
theme: PaperMod
pagination:
  pagerSize: 5

params:
  disableReadOtherPosts: false
  enableSharingButtons: true
  showPostNavLinks: true
  assets:
    disableHLJS: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

Params:
  ShowReadingTime: true


menu:
  main:
    - identifier: posts
      name : Posts
      url: /posts/
      weight: 10
    - identifier: tags
      name : Tags
      url: /tags/
      weight: 20
    - name: Search
      url: /search/
      weight: 25
    - name: About
      url: /about/
      weight: 30

markup:
  highlight:
      style: solarized-dark
  goldmark:
    renderer:
      unsafe: true