baseURL = "https://example.com"
languageCode = "en"
title = "Bruno Blog"
defaultContentLanguage = "en"

[module]
  [[module.imports]]
    path = "github.com/barklan/hugo-dead-simple"

[params]
  author = "Bruno Teixeira"
  description = "My personal blog"
  email = "brunoalexandre3@hotmail.com"

[menu]

  [[menu.main]]
    name = "<u>H</u>ome"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "<u>T</u>ags"
    url = "/tags"
    weight = 2

  [[menu.main]]
    name = "<u>A</u>bout"
    url = "/about"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

enableGitInfo = true

[markup.highlight]
  codeFences = true
  style = "monokai"
  lineNumbersInTable = false
  noClasses = true